COMPANIES = {
    "google": "Google",
    "amazon": "Amazon",
    "microsoft": "Microsoft",
    "meta": "Meta",
    "apple": "Apple",
    "netflix": "Netflix",
    "uber": "Uber",
    "atlassian": "Atlassian",
    "adobe": "Adobe",
    "oracle": "Oracle",
    "salesforce": "Salesforce",
    "vmware": "VMware",
    "intuit": "Intuit",
    "linkedin": "LinkedIn",
    "phonepe": "PhonePe",
    "flipkart": "Flipkart",
    "razorpay": "Razorpay",
    "swiggy": "Swiggy",
    "zomato": "Zomato",
    "paytm": "Paytm",
    "opentext": "OpenText",
}