ROLES = {
    "frontend_engineer": "Frontend Engineer",
    "backend_engineer": "Backend Engineer",
    "full_stack_engineer": "Full Stack Engineer",
    "software_engineer": "Software Engineer",
    "mobile_developer": "Mobile Developer",
    "devops_engineer": "DevOps Engineer",
    "cloud_engineer": "Cloud Engineer",
    "data_engineer": "Data Engineer",
    "ml_engineer": "Machine Learning Engineer",
    "ai_engineer": "AI Engineer",
    "game_developer": "Game Developer",
    "embedded_engineer": "Embedded Software Engineer",
    "security_engineer": "Security Engineer",
    "qa_engineer": "QA Engineer",
}