services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env

  interview-prep-backend:
    build:
      context: ./interview-prep-backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    env_file:
      - ./interview-prep-backend/.env
    depends_on:
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_BACKEND_URL=http://localhost:5000/api/v1
      - VITE_INTERVIEW_PREP_URL=http://localhost:5001
    stdin_open: true
    tty: true
    depends_on:
      - backend
      - interview-prep-backend