from datetime import datetime, timezone

from fastapi import APIRouter, Depends, HTTPException, BackgroundTasks, status
from sqlmodel import select
from sqlmodel.ext.asyncio.session import AsyncSession
from sqlalchemy.orm.attributes import flag_modified
from sqlalchemy.orm import selectinload

from app.models import User, Problem, Note
from app.schemas import SaveNoteRequest
from app.utils import track_user_activity_task
from app.middlewares import get_current_user
from app.database import get_session

router = APIRouter(prefix="/notes", tags=["Study Notes Management"])


@router.post("/save")
async def save_note(
    payload: SaveNoteRequest,
    background_tasks: BackgroundTasks,
    current_user: User = Depends(get_current_user),
    session: AsyncSession = Depends(get_session)
):
    """
    Saves or updates a user's study notes for a specific problem.
    """
    if not payload.problem_id:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Problem id is missing."
        )

    # 1. Verify the problem exists and belongs to the user
    problem_statement = select(Problem).where(
        Problem.id == payload.problem_id,
        Problem.user_id == current_user.id
    )
    problem_result = await session.execute(problem_statement)
    if not problem_result.scalar_one_or_none():
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Problem reference not found."
        )

    # 2. Check for an existing note record
    note_statement = select(Note).where(
        Note.problem_id == payload.problem_id,
        Note.user_id == current_user.id
    )
    note_result = await session.execute(note_statement)
    note = note_result.scalar_one_or_none()
    
    # A note is brand new if no database record exists, or it was just a blank background processing shell
    is_new_note = note is None or not note.bruteForce

    if not note:
        note = Note(
            problem_id=payload.problem_id,
            user_id=current_user.id
        )

    # 3. Map values across from payload schemas
    note.bruteForce = [block.model_dump() for block in payload.bruteForce]
    note.optimalApproach = [block.model_dump() for block in payload.optimalApproach]
    note.algorithm = [step.model_dump() for step in payload.algorithm]
    note.dryRun = [step.model_dump() for step in payload.dryRun]
    note.edgeCases = [case.model_dump() for case in payload.edgeCases]

    note.status = payload.status or "draft"
    note.lastEditedAt = datetime.now(timezone.utc)

    # 4. Notify SQLAlchemy of array modifications
    flag_modified(note, "bruteForce")
    flag_modified(note, "optimalApproach")
    flag_modified(note, "algorithm")
    flag_modified(note, "dryRun")
    flag_modified(note, "edgeCases")

    session.add(note)
    await session.commit()
    await session.refresh(note)

    # 5. Track user metrics asynchronously if this is their first time saving
    if is_new_note:
        background_tasks.add_task(
            track_user_activity_task,
            current_user.id, 
            "note"
        )

    return {
        "success": True,
        "message": f"Note saved successfully as a {note.status}.",
        "note": note
    }


@router.get("/user")
async def get_all_notes_by_user(
    current_user: User = Depends(get_current_user),
    session: AsyncSession = Depends(get_session)
):
    """
    Retrieves all finalized or draft notes saved by the logged-in user.
    """
    statement = (
        select(Note)
        .where(Note.user_id == current_user.id)
        .options(selectinload(Note.problem))
        .order_by(Note.createdAt.desc())
    )

    results = await session.execute(statement)
    notes = results.scalars().all()

    formatted_notes = []

    for n in notes:
        # Hide uncompiled background jobs from the user's primary dashboard list feed
        if n.status == "processing":
            continue

        note_dict = n.model_dump()

        if n.problem:
            note_dict["problem"] = {
                "id": n.problem.id,
                "title": n.problem.title,
                "platform": n.problem.platform,
                "difficulty": n.problem.difficulty,
                "language": n.problem.language
            }

        formatted_notes.append(note_dict)

    return {
        "success": True,
        "count": len(formatted_notes),
        "notes": formatted_notes
    }


@router.get("/{problem_id}")
async def get_note_by_problem(
    problem_id: int,
    current_user: User = Depends(get_current_user),
    session: AsyncSession = Depends(get_session)
):
    """
    Fetches a note associated with a specific problem ID.
    """
    statement = select(Note).where(
        Note.problem_id == problem_id,
        Note.user_id == current_user.id
    )

    result = await session.execute(statement)
    note = result.scalar_one_or_none()

    # Block access if the note is still being generated by the AI thread
    if not note or note.status == "processing":
        return {
            "success": False,
            "message": "No saved notes exist yet for this specified problem item.",
            "note": None
        }

    return {
        "success": True,
        "note": note
    }


@router.get("/id/{note_id}")
async def get_note_by_id(
    note_id: int,
    current_user: User = Depends(get_current_user),
    session: AsyncSession = Depends(get_session)
):
    """
    Fetches a specific note directly by its internal Note ID.
    """
    query = select(Note).where(
        Note.id == note_id,
        Note.user_id == current_user.id
    )

    result = await session.execute(query)
    note = result.scalar_one_or_none()

    if not note or note.status == "processing":
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Note record not found"
        )

    return {
        "success": True,
        "note": note
    }