import React from "react";
import { renderToString } from "react-dom/server"; 
import DOMPurify from "dompurify";
import CodeContainer from "../components/common/CodeContainer"

export const parseRawHtml = (rawHtml) => {
  if (!rawHtml || rawHtml.trim() === "") return "";

  const parser = new DOMParser();
  const doc = parser.parseFromString(rawHtml, "text/html");

  // 1. Target any live editor placeholder widgets left behind
  doc.querySelectorAll(".algonotes-editor-placeholder-card")
  .forEach((widget) => {
    widget.remove();
  });

  // 2. FRONTEND-ONLY SAFE IMAGE CLEANUP
  // Targets exactly the "image-placeholder-[number]" pattern generated by your AI prompt
  doc.querySelectorAll('img[src^="image-placeholder-"]').forEach((img) => {
    const nextNode = img.nextElementSibling;
    if (nextNode && nextNode.classList.contains("algonotes-image-description")) {
      nextNode.remove();
    }
    img.remove();
  });

  // 3. DYNAMIC CODE RENDERING INTERCEPTION
  doc.querySelectorAll(".algonotes-pre").forEach((preElement) => {
    const codeElement = preElement.querySelector(".algonotes-code-block");
    if (codeElement) {
      const rawCodeText = codeElement.textContent; 

      const highlightedHtmlString = renderToString(
        <CodeContainer code={rawCodeText} />
      );

      const tempContainer = doc.createElement("div");
      tempContainer.innerHTML = highlightedHtmlString;
      const newCodeNode = tempContainer.firstChild;

      if (newCodeNode) {
        preElement.parentNode.replaceChild(newCodeNode, preElement);
      }
    }
  });

  // 4. 🛡️ XSS SANITIZATION
  const cleanHtml = DOMPurify.sanitize(doc.body.innerHTML, {
    ALLOWED_TAGS: [
      'p', 'br', 'strong', 'em', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 
      'ul', 'ol', 'li', 'span', 'div', 'pre', 'code', 'table', 'thead', 
      'tbody', 'tr', 'th', 'td', 'img' 
    ],
    ALLOWED_ATTR: [
      'class', 'id', 'style', 'src', 'alt', 'width', 'height', 'loading'
    ], 
  });

  return cleanHtml;
};