from .base_prompt import (
    SYSTEM_PROMPT,
    QUESTION_RULES,
    PROJECT_RULES,
    EVALUATION_RULES,
    JSON_RULES,
)

from .resume_prompt import RESUME_INTERVIEW_PROMPT
from .company_prompt import COMPANY_INTERVIEW_PROMPT
from .project_prompt import PROJECT_INTERVIEW_PROMPT
from .evaluation_prompt import INTERVIEW_EVALUATION_PROMPT
from .report_prompt import INTERVIEW_REPORT_PROMPT

__all__ = [
    "SYSTEM_PROMPT",
    "QUESTION_RULES",
    "PROJECT_RULES",
    "EVALUATION_RULES",
    "JSON_RULES",
    "RESUME_INTERVIEW_PROMPT",
    "COMPANY_INTERVIEW_PROMPT",
    "PROJECT_INTERVIEW_PROMPT",
    "INTERVIEW_EVALUATION_PROMPT",
    "INTERVIEW_REPORT_PROMPT",
]